name = "Numbers"
uuid = "fdcbc02e-b943-4a86-96c7-d7dc4218024c"
authors = ["yorche <hyaoki123@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
